### ISSUE TITLE
We are almost there Team! 🏆 

### ISSUE THREAD

**Issue by EmcSquared07** [parkchaewonn/CRUSADERS-Calculator#6]
Hello peeps! As you can see, our calculator is improving 👯. @parkchaewonn  is also working already in the logic codes. Btw, can I ask for suggestions of what should be done in the remaining space? I really don't have the idea as of now. If you have the suggestions, just beep back in this issue. 🥰 

@RichmarAgum 
@chrisdevoir 
@DadoTennyson05 
@parkchaewonn 

Let's keep it up peeps! Fighting!

![Screenshot (78)](https://user-images.githubusercontent.com/83933430/124383781-e7956c00-dd00-11eb-9d44-e29f5b27dfe7.png)

**Comment by RichmarAgum** [comment]
Maybe we can add a square root button :D

**Comment by chrisdevoir** [comment]
I agree with the idea of putting a square root button and  maybe we can also add an exponent button. I also suggest to  improve the color/visuals to make the calculator stylish.

**Comment by EmcSquared07** [comment]
Yahyah. Sure 😃 We can have it. Maybe @chrisdevoir you can suggest the best color combinations for our calculator. 😉 Artist yarn ehhh
